import AppKit

/// What the watcher needs from a pasteboard, so tests can drive it.
protocol PasteboardReading: AnyObject {
    var changeCount: Int { get }
    func currentTypes() -> [String]
    func currentString() -> String?
    func currentData(forType type: String) -> Data?
}

extension NSPasteboard: PasteboardReading {
    func currentTypes() -> [String] { (types ?? []).map(\.rawValue) }
    func currentString() -> String? { string(forType: .string) }
    func currentData(forType type: String) -> Data? { data(forType: PasteboardType(type)) }
}

/// One copy, as the history takes it.
enum Copied: Equatable {
    case text(String)
    /// The picture's bytes as copied, and the pasteboard type they came as.
    case image(Data, type: String)
}

/// Which copies belong in the history, and as what.
enum PasteboardFilter {
    enum Kind: Equatable {
        case text
        case image(type: String)
    }

    /// Markers password managers and similar apps put on copies that must not
    /// be kept — the nspasteboard.org convention plus the vendors that predate it.
    static let privateMarkers: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
    ]

    static let textTypes: Set<String> = ["public.utf8-plain-text", "NSStringPboardType"]

    /// In order of preference: compressed formats before TIFF, which the same
    /// copy often carries too.
    static let imageTypes = ["public.png", "public.jpeg", "public.heic", "public.tiff", "com.compuserve.gif"]

    /// A copied file carries its icon as a picture; that is not an image the
    /// user copied.
    static let fileTypes: Set<String> = ["public.file-url", "NSFilenamesPboardType"]

    /// Text first: a spreadsheet range or a rich-text selection carries a
    /// picture of itself, and the words are what the user copied.
    static func kind(of types: [String]) -> Kind? {
        let set = Set(types)
        guard set.isDisjoint(with: privateMarkers) else { return nil }
        if !set.isDisjoint(with: textTypes) { return .text }
        return imageType(in: set).map { .image(type: $0) }
    }

    static func imageType(in types: Set<String>) -> String? {
        guard types.isDisjoint(with: fileTypes) else { return nil }
        return imageTypes.first(where: types.contains)
    }

    /// A single web or file address and nothing else.
    static func isLink(_ text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.contains(where: \.isWhitespace),
              let scheme = URL(string: trimmed)?.scheme?.lowercased() else { return false }
        return ["http", "https", "file"].contains(scheme)
    }
}

/// Notices copies by polling the pasteboard's change count — the only way
/// macOS offers, and nearly free: an integer read twice a second. Content is
/// read only when the count moved and the copy is not marked private.
@MainActor
final class ClipboardWatcher {
    private let pasteboard: PasteboardReading
    private let frontmostApp: () -> String?
    private var lastSeen = 0
    private var ignoredChangeCount: Int?
    private var timer: Timer?

    var onCopy: ((Copied, String?) -> Void)?

    init(pasteboard: PasteboardReading = NSPasteboard.general,
         frontmostApp: @escaping () -> String? = {
             NSWorkspace.shared.frontmostApplication?.localizedName
         }) {
        self.pasteboard = pasteboard
        self.frontmostApp = frontmostApp
    }

    var isRunning: Bool { timer != nil }

    /// Takes the current contents as already seen.
    func prime() {
        lastSeen = pasteboard.changeCount
    }

    func start() {
        stop()
        prime()
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        // Lets the system batch the wake-ups with other work.
        timer.tolerance = 0.25
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// For ScreenHere's own writes, which are added to the history directly.
    func ignore(changeCount: Int) {
        ignoredChangeCount = changeCount
    }

    func poll() {
        let count = pasteboard.changeCount
        guard count != lastSeen else { return }
        lastSeen = count
        if count == ignoredChangeCount { return }
        let types = pasteboard.currentTypes()
        guard let kind = PasteboardFilter.kind(of: types), let copied = read(kind, types: types) else { return }
        onCopy?(copied, frontmostApp())
    }

    private func read(_ kind: PasteboardFilter.Kind, types: [String]) -> Copied? {
        switch kind {
        case .image(let type):
            return pasteboard.currentData(forType: type).map { .image($0, type: type) }
        case .text:
            guard let text = pasteboard.currentString() else { return nil }
            // A browser's "Copy Image" adds the picture's address as text.
            if PasteboardFilter.isLink(text),
               let type = PasteboardFilter.imageType(in: Set(types)),
               let data = pasteboard.currentData(forType: type) {
                return .image(data, type: type)
            }
            return .text(text)
        }
    }
}
